


### Get loging user
GET http://localhost:3000/users/?email=too&password=too&day=456331



### logout
GET http://localhost:3000/users/logout
Content-Type: application/json


### Create a new user
POST http://localhost:3000/users/new
Content-Type: application/json

{
  "day": "test",
  "email": "test2",
  "password": "password123"
}



### update session 
PUT http://localhost:3000/poo/update
Content-Type: application/json

{
  "userId": "6791e0d52322876061583c58",
  "day": "test",
  "times": [222,3232,233233]
}

###
DELETE  http://localhost:3000/users/6791c84e7e018b9869478082






